DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATION BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC,
    lon NUMERIC
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATION BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(250) NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR,
    category INTEGER REFERENCES categories (id) ON DELETE CASCADE,
    description VARCHAR,
    created_on TIMESTAMP,
    event_date TIMESTAMP,
    published_on TIMESTAMP,
    location BIGINT REFERENCES locations (id) ON DELETE CASCADE,
    paid BOOLEAN,
    participant_limit INTEGER,
    confirmed_requests INTEGER,
    initiator BIGINT REFERENCES users (id) ON DELETE CASCADE,
    request_moderation BOOLEAN,
    title BOOLEAN,
    state VARCHAR,
    views INTEGER
);